# --- General options --- #

url: "https://shawnpence.com"
baseurl: ""

title: Shawn P Pence

description: Shawn P Pence, Software Developer

avatar: "/img/shawn_pence_small.jpg"
avatar-alt-text: "picture of Shawn"
favicon: "/img/favicon_32.png"

author:
  name: Shawn P Pence
  twitter: ShawnPPence

social-links:
  twitter: ShawnPPence
  linkedin: shawnpence
  github: ShawnPence
#  stackoverflow: "10593386/shawn-pence"

timezone: "America/Chicago"

max_excerpt_length: 30

# --- Should not need to change below this line --- #

# Output options (more information on Jekyll's site)
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

